baseURL = "https://liebechaos.org/"
languageCode = "en-us"
title = "Liebe Chaos Verein"
theme = "amsel"

[params]
  mainSections = ["activites", "reflections"]

[markup.goldmark.renderer]
unsafe= true